#!/usr/bin/env bash

declare -A OKMORSE

OKMORSE[a]='oklookingforward'
OKMORSE[b]='lookingforwardokokok'
OKMORSE[c]='lookingforwardoklookingforwardok'
OKMORSE[d]='lookingforwardokok'
OKMORSE[e]='ok'
OKMORSE[f]='okoklookingforwardok'
OKMORSE[g]='lookingforwardlookingforwardok'
OKMORSE[h]='okokokok'
OKMORSE[i]='okok'
OKMORSE[j]='oklookingforwardlookingforwardlookingforward'
OKMORSE[k]='lookingforwardoklookingforward'
OKMORSE[l]='oklookingforwardokok'
OKMORSE[m]='lookingforwardlookingforward'
OKMORSE[n]='lookingforwardok'
OKMORSE[o]='lookingforwardlookingforwardlookingforward'
OKMORSE[p]='oklookingforwardlookingforwardok'
OKMORSE[q]='lookingforwardlookingforwardoklookingforward'
OKMORSE[r]='oklookingforwardok'
OKMORSE[s]='okokok'
OKMORSE[t]='lookingforward'
OKMORSE[u]='okoklookingforward'
OKMORSE[v]='okokoklookingforward'
OKMORSE[w]='oklookingforwardlookingforward'
OKMORSE[x]='lookingforwardokoklookingforward'
OKMORSE[y]='lookingforwardoklookingforwardlookingforward'
OKMORSE[z]='lookingforwardlookingforwardokok'
OKMORSE[0]='lookingforwardlookingforwardlookingforwardlookingforwardlookingforward'
OKMORSE[1]='oklookingforwardlookingforwardlookingforwardlookingforward'
OKMORSE[2]='okoklookingforwardlookingforwardlookingforward'
OKMORSE[3]='okokoklookingforwardlookingforward'
OKMORSE[4]='okokokoklookingforward'
OKMORSE[5]='okokokokok'
OKMORSE[6]='lookingforwardokokokok'
OKMORSE[7]='lookingforwardlookingforwardokokok'
OKMORSE[8]='lookingforwardlookingforwardlookingforwardokok'
OKMORSE[9]='lookingforwardlookingforwardlookingforwardlookingforwardok'
OKMORSE[_]='/'
